// monsters.h - X macro monster data (see https://wikipedia.org/wiki/X_Macro)

X(NO_MONSTER,   NULL,       NULL,         9, 1,  0,  true, 999,  NONE,  0)

X(GREEN_SLIME,  GREEN "P",  slime,        9, 1,  0, false, 999,  NONE, 63)
X(BLUE_SLIME,   BLUE "P",   slime,        2, 2,  1, false, 999,  NONE, 32)
X(YELLOW_SLIME, YELLOW "P", slime,        1, 1,  0, false, 999,  NONE, 14)
X(FIRE_SLIME,   RED "P",    slime,        3, 1,  0, false, 999, STONE, 34)
X(ICE_SLIME,    CYAN "P",   slime,        3, 1,  0, false, 999, STONE, 34)
X(PURPLE_SLIME, PURPLE "P", slime,        3, 1,  0, false, 999,  NONE, 35)
X(BLACK_SLIME,  BLACK "P",  slime,        3, 1,  0, false, 999,  NONE, 35)

X(SKELETON_1,   "Z",        basic_seek,   1, 1,  1, false,   9,  NONE, 18)
X(SKELETON_2,   YELLOW "Z", basic_seek,   3, 2,  1, false,   9,  NONE, 40)
X(SKELETON_3,   BLACK "Z",  basic_seek,   4, 3,  1, false,   9,  NONE, 55)
X(HEADLESS_2,   YELLOW "∠", charge,       3, 1,  0, false,   0,  NONE,  0)
X(HEADLESS_3,   BLACK "∠",  charge,       4, 1,  0, false,   0,  NONE,  0)
X(BLUE_BAT,     BLUE "B",   bat,          1, 1,  1,  true,   9,  NONE, 18)
X(RED_BAT,      RED "B",    bat,          2, 1,  0,  true,   9,  NONE, 24)
X(GREEN_BAT,    GREEN "B",  green_bat,    3, 1,  0,  true,   9,  NONE, 36)
X(BLACK_BAT,    BLACK "B",  black_bat,    2, 1,  0,  true,   9,  NONE, 48)
X(MONKEY_1,     PURPLE "Y", basic_seek,   0, 1,  0, false,   9,  NONE, 10)
X(MONKEY_2,     "Y",        basic_seek,   0, 2,  0, false,   9,  NONE, 12)
X(CONF_MONKEY,  GREEN "Y",  basic_seek,   0, 1,  0, false,   9,  NONE, 11)
X(TELE_MONKEY,  PINK "Y",   basic_seek,   0, 2,  0, false,   9,  NONE,  7)
X(GHOST,        "8",        ghost,        2, 1,  0,  true,   9,  NONE, 23)
X(ZOMBIE,       GREEN "Z",  zombie,       2, 1,  1, false, 999,  NONE, 25)
X(WRAITH,       RED "W",    basic_seek,   1, 1,  0,  true,   9,  NONE, 14)
X(WIGHT,        GREEN "W",  basic_seek,   2, 1,  0,  true,  25,  NONE, 24)
X(GHAST,        PURPLE "W", basic_seek,   2, 1,  0,  true,  49,  NONE, 23)
X(GHOUL,        "W",        moore_seek,   1, 1,  0,  true,   9,  NONE, 35)
X(CURSE_WRAITH, YELLOW "W", basic_seek,   0, 1,  0,  true,   9,  NONE,  5)
X(MIMIC_1,      ORANGE "m", mimic,        2, 1,  0, false,   1,  NONE, 22)
X(MIMIC_2,      BLUE "m",   mimic,        3, 1,  0, false,   1,  NONE, 33)
X(WHITE_MIMIC,  "m",        mimic,        3, 1,  0, false,   1,  NONE, 33)
X(WALL_MIMIC,   GREEN "m",  mimic,        2, 1,  0, false,   1,  NONE, 24)
X(FIRE_MIMIC,   RED "m",    mimic,        2, 1,  0, false,   1,  NONE, 23)
X(ICE_MIMIC,    CYAN "m",   mimic,        2, 1,  0, false,   1,  NONE, 23)
X(MIMIC_STATUE, BLACK "g",  mimic,        4, 1,  0, false,   1,  NONE, 46)
X(SHOP_MIMIC,   YELLOW "m", moore_mimic,  2, 1,  0, false,   2,  NONE, 22)

X(SKELETANK_1,  "Ź",        basic_seek,   1, 1,  1, false,  25,  NONE, 18)
X(SKELETANK_2,  YELLOW "Ź", basic_seek,   3, 2,  1, false,  25,  NONE, 41)
X(SKELETANK_3,  BLACK "Ź",  basic_seek,   5, 3,  1, false,  25,  NONE, 60)
X(WINDMAGE_1,   BLUE "@",   wind_mage,    2, 1,  1, false,   0,  NONE, 26)
X(WINDMAGE_2,   YELLOW "@", wind_mage,    4, 2,  1, false,   0,  NONE, 52)
X(WINDMAGE_3,   BLACK "@",  wind_mage,    5, 3,  1, false,   0,  NONE, 60)
X(MUSHROOM_1,   BLUE "F",   mushroom,     2, 1,  3, false,  25,  NONE, 28)
X(MUSHROOM_2,   PURPLE "F", mushroom,     4, 3,  2, false,  25,  NONE, 56)
X(GOLEM_1,      "'",        basic_seek,   4, 5,  3,  true,  25, STONE, 66)
X(GOLEM_2,      BLACK "'",  basic_seek,   6, 7,  3,  true,  25, STONE, 68)
X(ARMADILLO_1,  "q",        armadillo,    2, 1,  0, false,  -1, STONE, 23)
X(ARMADILLO_2,  YELLOW "q", armadillo,    3, 2,  0, false,  -1, STONE, 39)
X(ARMADILDO,    ORANGE "q", armadillo,    3, 3,  0, false,  -1, STONE, 42)
X(CLONE,        "@",        clone,        3, 1,  0, false,  25,  NONE, 35)
X(TARMONSTER,   "t",        tarmonster,   3, 1,  0,  true,   1,  NONE, 44)
X(MOLE,         "r",        mole,         2, 1,  0,  true,  25,  NONE,  3)
X(LIGHTSHROOM,  "F",        NULL,         0, 1,  0, false,   0,  NONE,  0)
X(BOMBSHROOM,   YELLOW "F", NULL,         4, 1,  0, false,  25,  NONE, 86)
X(BOMBSHROOM_,  RED "F",    explosion,    4, 1,  0, false,  25,  NONE, 86)

X(RIDER_1,      "&",        basic_seek,   2, 1,  0,  true,  49,  NONE, 23)
X(RIDER_2,      YELLOW "&", basic_seek,   4, 2,  0,  true,  49,  NONE, 51)
X(RIDER_3,      BLACK "&",  basic_seek,   6, 3,  0,  true,  49,  NONE, 62)
X(EFREET,       RED "E",    basic_seek,   3, 2,  2,  true,  49, STONE, 65)
X(DJINN,        CYAN "E",   basic_seek,   3, 2,  2,  true,  49, STONE, 65)
X(ASSASSIN_1,   PURPLE "o", assassin,     4, 1,  0, false,  49,  NONE, 47)
X(ASSASSIN_2,   BLACK "o",  assassin,     6, 2,  0, false,  49,  NONE, 61)
X(FIRE_BEETLE,  RED "a",    basic_seek,   3, 3,  1, false,  49,  NONE, 43)
X(ICE_BEETLE,   CYAN "a",   basic_seek,   3, 3,  1, false,  49,  NONE, 43)
X(BEETLE,       "a",        basic_seek,   3, 3,  1, false,  49,  NONE, 43)
X(HELLHOUND,    RED "d",    moore_seek,   3, 1,  1, false,  49,  NONE, 37)
X(SHOVE_1,      PURPLE "p", basic_seek,   0, 2,  0, false,  49,  NONE,  6)
X(SHOVE_2,      BLACK "p",  basic_seek,   0, 3,  0, false,  49,  NONE,  9)
X(YETI,         CYAN "Y",   yeti,         3, 1,  3,  true,  49, STONE, 64)
X(FIRE_POT,     RED "(",    NULL,         0, 1,  0, false,   0,  NONE,  0)
X(ICE_POT,      CYAN "(",   NULL,         0, 1,  0, false,   0,  NONE,  0)

X(BOMBER,       RED "o",    diagonal_seek,4, 1,  1, false,   0,  NONE, 84)
X(DIGGER,       "o",        digger,       1, 1,  0, false,   9, STONE, 17)
X(BLADENOVICE,  "b",        blademaster,  1, 1,  1, false,   9,  NONE, 81)
X(BLADEMASTER,  YELLOW "b", blademaster,  2, 2,  1, false,   9,  NONE, 82)
X(GOOLEM,       GREEN "'",  basic_seek,   5, 5,  3,  true,   9, STONE, 67)
X(HARPY,        GREEN "h",  harpy,        3, 1,  1,  true,   0,  NONE, 38)
X(LICH_1,       GREEN "L",  lich,         2, 1,  1, false,   0,  NONE, 57)
X(LICH_2,       PURPLE "L", lich,         3, 2,  1, false,   0,  NONE, 58)
X(LICH_3,       BLACK "L",  lich,         4, 3,  1, false,   0,  NONE, 59)
X(PIXIE,        "n",        basic_seek,   4, 1,  0,  true,   0,  NONE, 46)
X(SARCO_1,      "|",        sarcophagus,  0, 1,  7, false,   9,  NONE, 19)
X(SARCO_2,      YELLOW "|", sarcophagus,  0, 2,  9, false,   9,  NONE, 20)
X(SARCO_3,      BLACK "|",  sarcophagus,  0, 3, 11, false,   9,  NONE, 21)
X(SPIDER,       YELLOW "s", basic_seek,   2, 1,  1, false,   9,  NONE, 49)
X(FREE_SPIDER,  RED "s",    diagonal_seek,2, 1,  0, false,   9,  NONE, 49)
X(WARLOCK_1,    "w",        basic_seek,   3, 1,  1, false,   9,  NONE, 49)
X(WARLOCK_2,    YELLOW "w", basic_seek,   4, 2,  1, false,   9,  NONE, 50)
X(MUMMY,        "M",        moore_seek,   2, 1,  1, false,   9,  NONE, 69)
X(WIND_STATUE,  CYAN "g",   wind_statue,  4, 1,  0, false,   0,  NONE, 46)
X(BOMB_STATUE,  YELLOW "g", bomb_statue,  4, 1,  0, false,   0,  NONE, 46)
X(MINE_STATUE,  RED "g",    NULL,         4, 1,  0, false,   0,  NONE,  0)

X(WATER_BALL,   BLUE "e",   moore_seek,   0, 1,  0,  true,   9,  NONE,  4)
X(TAR_BALL,     BLACK "e",  moore_seek,   0, 1,  0,  true,   9,  NONE,  5)
X(ELECTRO_1,    BLUE "L",   electro_lich, 1, 1,  1, false,   0,  NONE, 18)
X(ELECTRO_2,    RED "L",    electro_lich, 3, 2,  1, false,   0,  NONE, 40)
X(ELECTRO_3,    YELLOW "L", electro_lich, 4, 3,  1, false,   0,  NONE, 55)
X(ORB_1,        YELLOW "e", orb,          1, 1,  0,  true, 999,  DIRT, 13)
X(ORB_2,        YELLOW "e", orb,          3, 1,  0,  true, 999,  DIRT, 33)
X(ORB_3,        YELLOW "e", orb,          4, 1,  0,  true, 999,  DIRT, 45)
X(WIRE_ZOMBIE,  ORANGE "Z", wire_zombie,  2, 1,  0, false, 999,  NONE, 25)
X(SKULL_1,      WHITE "z",  basic_seek,   1, 1,  1, false,   9,  NONE, 16)
X(SKULL_2,      YELLOW "z", basic_seek,   2, 1,  1, false,   9,  NONE, 31)
X(SKULL_3,      BLACK "z",  basic_seek,   4, 1,  1, false,   9,  NONE, 54)
X(GORGON_1,     GREEN "S",  basic_seek,   0, 1,  0, false,   9,  NONE,  5)
X(GORGON_2,     YELLOW "S", basic_seek,   0, 3,  0, false,   9,  NONE,  8)
X(STONE_STATUE, BLACK "S",  NULL,         1, 1,  0, false,   0,  NONE,  0)
X(GOLD_STATUE,  BLACK "S",  NULL,         1, 3,  0, false,   0,  NONE,  0)
X(EVIL_EYE_1,   GREEN "e",  evil_eye,     1, 1,  0,  true,   0, STONE, 15)
X(EVIL_EYE_2,   PINK "e",   evil_eye,     2, 2,  0,  true,   0, STONE, 30)
X(ORC_1,        GREEN "ô",  orc,          1, 1,  0, false,   9,  NONE, 14)
X(ORC_2,        PINK "ô",   orc,          2, 2,  0, false,   9,  NONE, 29)
X(ORC_3,        PURPLE "ô", orc,          3, 3,  0, false,   9,  NONE, 42)
X(DEVIL_1,      RED "&",    devil,        2, 1,  2, false,   9,  NONE, 27)
X(DEVIL_2,      GREEN "&",  devil,        4, 2,  2, false,   9,  NONE, 53)

X(DIREBAT_1,    YELLOW "B", bat,          3, 2,  1,  true,   9,  NONE, 70)
X(DIREBAT_2,    "B",        bat,          4, 3,  1,  true,   9,  NONE, 74)
X(DRAGON,       GREEN "D",  basic_seek,   4, 4,  1,  true,  49,  SHOP, 75)
X(RED_DRAGON,   RED "D",    dragon,       6, 6,  0,  true, 100,  SHOP, 85)
X(BLUE_DRAGON,  BLUE "D",   dragon,       6, 6,  0,  true,   0,  SHOP, 83)
X(EARTH_DRAGON, BROWN "D",  basic_seek,   6, 8,  1,  true,   0,  SHOP, 80)
X(BANSHEE_1,    BLUE "8",   basic_seek,   4, 3,  0,  true,  -1,  NONE, 71)
X(BANSHEE_2,    GREEN "8",  basic_seek,   6, 4,  0,  true,  -1,  NONE, 79)
X(MINOTAUR_1,   "H",        minotaur,     4, 3,  0,  true,  49, STONE, 71)
X(MINOTAUR_2,   BLACK "H",  minotaur,     5, 5,  0,  true,  49, STONE, 77)
X(NIGHTMARE_1,  BLACK "u",  basic_seek,   4, 3,  1,  true,  81,  SHOP, 73)
X(NIGHTMARE_2,  RED "u",    basic_seek,   5, 5,  1,  true,  81,  SHOP, 78)
X(MOMMY,        BROWN "@",  mommy,        4, 6,  3,  true,   9,  NONE, 76)
X(OGRE,         GREEN "O",  ogre,         5, 5,  0,  true,   9, STONE, 77)
X(METROGNOME_1, YELLOW "G", metrognome,   4, 3,  0,  true,   9,  DIRT, 72)
X(METROGNOME_2, GREEN "G",  metrognome,   5, 5,  0,  true,   9,  DIRT, 77)

X(CRATE,        "(",        NULL,         0, 1,  0, false,   0,  NONE,  0)
X(BARREL,       BROWN "(",  charge,       1, 1,  0, false, 999,  DIRT,  2)
X(TEH_URN,      PURPLE "(", NULL,         0, 3,  0, false,   0,  NONE,  0)
X(CHEST,        BLACK "(",  NULL,         0, 1,  0, false,   0,  NONE,  0)
X(FIREPIG,      RED "q",    firepig,      5, 1,  0, false,   0,  NONE,  1)
X(SHOPKEEPER,   "@",        NULL,         0, 9,  0, false,   0,  NONE, 83)
X(PLAYER,       "@",        NULL,         1, 1,  0, false,   2,  DIRT, 99)
X(BOMB,         ORANGE "●", explosion,    4, 1,  0, false, 999,  NONE, 98)
X(SHRINE,       "_",        NULL,         0, 1,  0, false,   0,  NONE,  0)

#undef X
